In [1]:
import numpy as np
import pandas as pd
import nltk

In [2]:
data=pd.read_csv("/content/Preprocessed_DonorsChoose_dataset.csv")

In [3]:
data.head()

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
0,p253737,mrs,in,grades_prek_2,literacy_language,esl_literacy,0,0,154.60,23,educational support english learners home,students english learners working english seco...,students_need_opportunities_practice_beginning...,0.0
1,p258326,mr,fl,grades_6_8,history_civics_health_sports,civics_government_teamsports,7,1,299.00,1,wanted projector hungry learners,students arrive school eager learn polite gene...,students_need_projector_help_viewing_education...,0.0
2,p182444,ms,az,grades_6_8,health_sports,health_wellness_teamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,students_need_shine_guards_athletic_socks_socc...,0.0
3,p246581,mrs,ky,grades_prek_2,literacy_language_math_science,literacy_mathematics,4,1,232.90,4,techie kindergarteners,work unique school filled esl english second l...,students_need_engage_reading_math_way_inspire_...,0.0
4,p104768,mrs,tx,grades_prek_2,math_science,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,students_need_hands_practice_mathematics_fun_p...,0.0

In [4]:
data['project_is_approved'].value_counts()

project_is_approved
1    6620
0    1150
Name: count, dtype: int64

In [5]:
import pandas as pd
import string
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [6]:
import re

def clean_text_re(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9 ]','',text)
    return text

In [7]:
# Apply the new cleaning function to the relevant columns
data['cleaned_titles'] = data['cleaned_titles'].apply(clean_text_re)
data['cleaned_essays'] = data['cleaned_essays'].apply(clean_text_re)
data['cleaned_summary'] = data['cleaned_summary'].apply(clean_text_re)

# Display the updated DataFrame head to show the changes
display(data.head())

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
0,p253737,mrs,in,grades_prek_2,literacy_language,esl_literacy,0,0,154.60,23,educational support english learners home,students english learners working english seco...,studentsneedopportunitiespracticebeginningread...,0.0
1,p258326,mr,fl,grades_6_8,history_civics_health_sports,civics_government_teamsports,7,1,299.00,1,wanted projector hungry learners,students arrive school eager learn polite gene...,studentsneedprojectorhelpviewingeducationalpro...,0.0
2,p182444,ms,az,grades_6_8,health_sports,health_wellness_teamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,studentsneedshineguardsathleticsockssoccerball...,0.0
3,p246581,mrs,ky,grades_prek_2,literacy_language_math_science,literacy_mathematics,4,1,232.90,4,techie kindergarteners,work unique school filled esl english second l...,studentsneedengagereadingmathwayinspireminiipads,0.0
4,p104768,mrs,tx,grades_prek_2,math_science,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,studentsneedhandspracticemathematicsfunpersona...,0.0

In [8]:
data['project_grade_category'] = data['project_grade_category'].apply(clean_text_re)
data['project_subject_categories'] = data['project_subject_categories'].apply(clean_text_re)
data['project_subject_subcategories'] = data['project_subject_subcategories'].apply(clean_text_re)
display(data.head())

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary
0,p253737,mrs,in,gradesprek2,literacylanguage,eslliteracy,0,0,154.60,23,educational support english learners home,students english learners working english seco...,studentsneedopportunitiespracticebeginningread...,0.0
1,p258326,mr,fl,grades68,historycivicshealthsports,civicsgovernmentteamsports,7,1,299.00,1,wanted projector hungry learners,students arrive school eager learn polite gene...,studentsneedprojectorhelpviewingeducationalpro...,0.0
2,p182444,ms,az,grades68,healthsports,healthwellnessteamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,studentsneedshineguardsathleticsockssoccerball...,0.0
3,p246581,mrs,ky,gradesprek2,literacylanguagemathscience,literacymathematics,4,1,232.90,4,techie kindergarteners,work unique school filled esl english second l...,studentsneedengagereadingmathwayinspireminiipads,0.0
4,p104768,mrs,tx,gradesprek2,mathscience,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,studentsneedhandspracticemathematicsfunpersona...,0.0

In [9]:
# Identify columns to concatenate (all except 'project_is_approved')
feature_columns = [col for col in data.columns if col != 'project_is_approved']

# Convert all feature columns to string type to avoid errors during concatenation
for col in feature_columns:
    data[col] = data[col].astype(str)

# Concatenate the selected columns into a new 'concatenated_features' column
data['concatenated_features'] = data[feature_columns].apply(lambda x: ' '.join(x), axis=1)

# Display the head of the DataFrame with the new column
display(data[['concatenated_features', 'project_is_approved']].head())

                               concatenated_features  project_is_approved
0  p253737 mrs in gradesprek2 literacylanguage es...                    0
1  p258326 mr fl grades68 historycivicshealthspor...                    1
2  p182444 ms az grades68 healthsports healthwell...                    0
3  p246581 mrs ky gradesprek2 literacylanguagemat...                    1
4  p104768 mrs tx gradesprek2 mathscience mathema...                    1

In [10]:
def preprocess_text(text):
    # Ensure text is a string before processing
    if pd.isna(text):
        return []
    text = str(text)

    # 4 Tokenize
    tokens = nltk.word_tokenize(text)

    # 5 Remove stopwords
    stop_words = set(stopwords.words('english'))
    stop_word_removed = [word for word in tokens if word.lower() not in stop_words]

    # 6 Lemmatization
    lemmatizer = WordNetLemmatizer()
    lemmatized_text = [lemmatizer.lemmatize(word) for word in stop_word_removed]

    return lemmatized_text

data['concatenated_features'] = data['concatenated_features'].apply(preprocess_text)

data.head()

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary,concatenated_features
0,p253737,mrs,in,gradesprek2,literacylanguage,eslliteracy,0,0,154.6,23,educational support english learners home,students english learners working english seco...,studentsneedopportunitiespracticebeginningread...,0.0,"[p253737, mr, gradesprek2, literacylanguage, e..."
1,p258326,mr,fl,grades68,historycivicshealthsports,civicsgovernmentteamsports,7,1,299.0,1,wanted projector hungry learners,students arrive school eager learn polite gene...,studentsneedprojectorhelpviewingeducationalpro...,0.0,"[p258326, mr, fl, grades68, historycivicshealt..."
2,p182444,ms,az,grades68,healthsports,healthwellnessteamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,studentsneedshineguardsathleticsockssoccerball...,0.0,"[p182444, m, az, grades68, healthsports, healt..."
3,p246581,mrs,ky,gradesprek2,literacylanguagemathscience,literacymathematics,4,1,232.9,4,techie kindergarteners,work unique school filled esl english second l...,studentsneedengagereadingmathwayinspireminiipads,0.0,"[p246581, mr, ky, gradesprek2, literacylanguag..."
4,p104768,mrs,tx,gradesprek2,mathscience,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,studentsneedhandspracticemathematicsfunpersona...,0.0,"[p104768, mr, tx, gradesprek2, mathscience, ma..."

In [11]:
data['clean_msg'] = data['concatenated_features'].apply(lambda x: ' '.join(x))
data.head()

,id,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,teacher_number_of_previously_posted_projects,project_is_approved,price,quantity,cleaned_titles,cleaned_essays,cleaned_summary,isdigit_summary,concatenated_features,clean_msg
0,p253737,mrs,in,gradesprek2,literacylanguage,eslliteracy,0,0,154.6,23,educational support english learners home,students english learners working english seco...,studentsneedopportunitiespracticebeginningread...,0.0,"[p253737, mr, gradesprek2, literacylanguage, e...",p253737 mr gradesprek2 literacylanguage esllit...
1,p258326,mr,fl,grades68,historycivicshealthsports,civicsgovernmentteamsports,7,1,299.0,1,wanted projector hungry learners,students arrive school eager learn polite gene...,studentsneedprojectorhelpviewingeducationalpro...,0.0,"[p258326, mr, fl, grades68, historycivicshealt...",p258326 mr fl grades68 historycivicshealthspor...
2,p182444,ms,az,grades68,healthsports,healthwellnessteamsports,1,0,516.85,22,soccer equipment awesome middle school students,true champions not always ones win guts mia ha...,studentsneedshineguardsathleticsockssoccerball...,0.0,"[p182444, m, az, grades68, healthsports, healt...",p182444 m az grades68 healthsports healthwelln...
3,p246581,mrs,ky,gradesprek2,literacylanguagemathscience,literacymathematics,4,1,232.9,4,techie kindergarteners,work unique school filled esl english second l...,studentsneedengagereadingmathwayinspireminiipads,0.0,"[p246581, mr, ky, gradesprek2, literacylanguag...",p246581 mr ky gradesprek2 literacylanguagemath...
4,p104768,mrs,tx,gradesprek2,mathscience,mathematics,1,1,67.98,4,interactive math tools,second grade classroom next year made around 2...,studentsneedhandspracticemathematicsfunpersona...,0.0,"[p104768, mr, tx, gradesprek2, mathscience, ma...",p104768 mr tx gradesprek2 mathscience mathemat...

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
print("TfidfVectorizer imported successfully.")

TfidfVectorizer imported successfully.

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,3))
X = tfidf_vectorizer.fit_transform(data['clean_msg'])
y = data['project_is_approved']

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
nb_model = MultinomialNB()
nb_model.fit(X_train,y_train)
y_pred = nb_model.predict(X_test)

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [15]:

from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
rf_model = RandomForestClassifier(n_estimators=50, random_state=42)
rf_model.fit(X_train,y_train)
y_pred = rf_model.predict(X_test)

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix
import numpy as np

In [17]:
# Initialize and train the Logistic Regression model
logistic_reg_model = LogisticRegression(solver='liblinear') # Using 'liblinear' solver for better convergence with TF-IDF features
logistic_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_logistic = logistic_reg_model.predict(X_test)

# Evaluate the model
print("Classification Report for Logistic Regression:")
print(classification_report(y_test, y_pred_logistic))
print("Confusion Matrix for Logistic Regression:")
print(confusion_matrix(y_test, y_pred_logistic))

# Display some predictions vs actual values (predictions will be 0 or 1)
predictions_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_logistic})
display(predictions_df.head())

Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

Confusion Matrix for Logistic Regression:
[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

      Actual  Predicted
1421       1          1
2748       0          1
3475       0          1
4851       1          1
3002       1          1

svm

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [19]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(class_weight="balanced")

svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8500643500643501
              precision    recall  f1-score   support

           0       0.40      0.01      0.02       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.63      0.50      0.47      1554
weighted avg       0.78      0.85      0.78      1554

[[   2  230]
 [   3 1319]]

XG BOOST

In [20]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [22]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [16:08:03] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

0.8494208494208494
              precision    recall  f1-score   support

           0       0.45      0.04      0.07       232
           1       0.85      0.99      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.65      0.52      0.49      1554
weighted avg       0.79      0.85      0.79      1554

[[   9  223]
 [  11 1311]]

# word2vec

In [23]:
!pip install gensim
from gensim.models import Word2Vec

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 75.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [25]:
import numpy as np

# First, correctly define corpus from the preprocessed text data
corpus = data['concatenated_features'].tolist()

# Then, train the Word2Vec model using this correct corpus
w2v_model = Word2Vec(sentences=corpus,
                     vector_size=50,
                     min_count = 1,
                     workers = 4, window = 3, sg=1)

def sentence_embedding(words):
  vectors = [w2v_model.wv[w] for w in words if w in w2v_model.wv]
  if len(vectors) == 0:
    return np.zeros(w2v_model.vector_size)
  else:
    return np.mean(vectors, axis=0)

# Finally, create embeddings
x_embeddings = np.array([sentence_embedding(msg) for msg in corpus])
print(x_embeddings.shape)

(7770, 50)

In [26]:
from sklearn.model_selection import train_test_split

X_w2v = x_embeddings
y = data['project_is_approved']
X_w2v_train, X_w2v_test, y_w2v_train, y_w2v_test = train_test_split(X_w2v, y, test_size=0.2, random_state=42)

# logistic regression

In [27]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_w2v_train, y_w2v_train)

y_pred = lr.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test, y_pred))
print(confusion_matrix(y_w2v_test, y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# random forest

In [28]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_w2v_train, y_w2v_train)
y_pred = rf_model.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test,y_pred))
print(confusion_matrix(y_w2v_test,y_pred))

0.8507078507078507
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       232
           1       0.85      1.00      0.92      1322

    accuracy                           0.85      1554
   macro avg       0.43      0.50      0.46      1554
weighted avg       0.72      0.85      0.78      1554

[[   0  232]
 [   0 1322]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# svm

In [29]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(class_weight="balanced")

svm_model.fit(X_w2v_train, y_w2v_train)
y_pred = svm_model.predict(X_w2v_test)

print(accuracy_score(y_w2v_test,y_pred))
print(classification_report(y_w2v_test,y_pred))
print(confusion_matrix(y_w2v_test,y_pred))

0.6280566280566281
              precision    recall  f1-score   support

           0       0.23      0.66      0.34       232
           1       0.91      0.62      0.74      1322

    accuracy                           0.63      1554
   macro avg       0.57      0.64      0.54      1554
weighted avg       0.81      0.63      0.68      1554

[[152  80]
 [498 824]]

In [31]:
from tensorflow.keras.layers import Input, Dense, Dropout, concatenate, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers

# Convert sparse TF-IDF matrix to dense, using X_train
X_tfidf_train_dense = X_train.toarray()

# TF-IDF Branch

input_tfidf = Input(shape=(X_tfidf_train_dense.shape[1],))

x1 = Dense(512, activation='relu',
           kernel_initializer='he_uniform',
           kernel_regularizer=regularizers.l2(0.001))(input_tfidf)
x1 = BatchNormalization()(x1)
x1 = Dropout(0.5)(x1)

x1 = Dense(256, activation='relu',
           kernel_initializer='he_uniform')(x1)
x1 = Dropout(0.4)(x1)

# Word2Vec Branch

input_w2v = Input(shape=(X_w2v_train.shape[1],))

x2 = Dense(256, activation='relu',
           kernel_initializer='glorot_uniform')(input_w2v)
x2 = BatchNormalization()(x2)
x2 = Dropout(0.4)(x2)

x2 = Dense(128, activation='relu')(x2)


# Merge Branches

merged = concatenate([x1, x2])

x = Dense(256, activation='relu',
          kernel_initializer='he_uniform')(merged)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

x = Dense(128, activation='relu')(x)
x = Dropout(0.4)(x)

# Output layer (Binary Classification)
output = Dense(1, activation='sigmoid')(x)

# Build Model
model = Model(inputs=[input_tfidf, input_w2v], outputs=output)

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 1359539)   │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │ 696,084,4… │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_1       │ (None, 50)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 512)       │      2,048 │ dense[0][0]       │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 256)       │     13,056 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 512)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256)       │      1,024 │ dense_2[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 256)       │    131,328 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 256)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 256)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 128)       │     32,896 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 384)       │          0 │ dropout_1[0][0],  │
│ (Concatenate)       │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 256)       │     98,560 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 256)       │      1,024 │ dense_4[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 256)       │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 128)       │     32,896 │ dropout_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_4 (Dropout) │ (None, 128)       │          0 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 1)         │        129 │ dropout_4[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 696,397,441 (2.59 GB)

 Trainable params: 696,395,393 (2.59 GB)

 Non-trainable params: 2,048 (8.00 KB)

### Enter Your Project Idea for Prediction

In [32]:
# Prompt the user for a new project idea
project_idea = input("Please enter your project idea: ")

# Apply the same preprocessing steps as the training data
# 1. Clean the text (using the clean_text_re function defined earlier)
cleaned_project_idea = clean_text_re(project_idea)

# 2. Preprocess the text (tokenization, stop-word removal, lemmatization)
preprocessed_tokens = preprocess_text(cleaned_project_idea)

# 3. Join the tokens back into a string for TF-IDF vectorization
processed_input_text = ' '.join(preprocessed_tokens)

print(f"\nOriginal Idea: {project_idea}")
print(f"Processed Input: {processed_input_text}")

Please enter your project idea: waste management from ships

Original Idea: waste management from ships
Processed Input: waste management ship

### Transform the Project Idea using TF-IDF and Predict Approval Status

In [33]:
# Transform the processed input text using the trained TF-IDF vectorizer
# The input to transform must be an iterable (e.g., a list containing the single string)
X_new = tfidf_vectorizer.transform([processed_input_text])

# Use the trained Logistic Regression model to predict the approval status
prediction = logistic_reg_model.predict(X_new)

# Interpret and print the prediction
if prediction[0] == 1:
    print("\nPrediction: This project idea is likely to be APPROVED.")
else:
    print("\nPrediction: This project idea is likely to be NOT APPROVED.")

Prediction: This project idea is likely to be APPROVED.